services:
    react-app:
        ports:
            - "80:80"
        restart: always
        build:
            context: .
            args:
                - REACT_APP_DJANGO_USERPROFILE_SERVICE=${REACT_APP_DJANGO_USERPROFILE_SERVICE}
                - REACT_APP_NODE_DESIGN_SERVICE=${REACT_APP_NODE_DESIGN_SERVICE}
        environment:
            - NODE_ENV=production
        volumes:
            - /var/app/current/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /var/app/current/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - /var/app/current/build:/usr/share/nginx/html:ro
